### ISSUE TITLE
Install creates dist-info dir but not package/module dir

### ISSUE THREAD

**Issue by bmcgough** [dokzlo13/dice_roller#1] opened 2024-09-24 00:23 UTC
Using Ubuntu 24.04 with default Python3, I do this:

- `python3 -m venv ~/venvs/somedice`
- `source ~/venvs/somedice/bin/activate`
- `pip3 install pydiceroll`

These complete without error. I then run python3 and try `from dice_roller import Dice` and get ModuleNotFoundError: No module named 'dice_roller' - same thing if I try pydiceroll or pydiceroller rather than dice_roller.

Looking in ~/venvs/somedice/lib/python3.12/site-packages, I see both module dirs and dist-info dirs for the required packages (like dyce), but see only a dist-info dir for pydiceroll.

For some reason, the actual module dir is not being created or installed. Are there different instructions for installation?

Thanks!

**Comment by dokzlo13** [comment] 2024-09-24 07:41
Hi, huge thanks for your interest in this project!

The issue was caused by a mistake during the transition from Poetry to setuptools/wheel. I’ve pushed a fix [here](https://github.com/dokzlo13/dice_roller/commit/d7135f46da7e1df56aa53358b129514a2d6accde) and updated the package on PyPI.

Please reinstall package, using new version 0.4.2 with:

```bash
pip uninstall pydiceroll
pip install pydiceroll==0.4.2
```

It should now work as expected. Let me know if you encounter any other issues!

**Closed as completed by dokzlo13** 2024-09-24 07:41 UTC

**Comment by bmcgough** [comment] 2024-09-24 17:16
Yep, all set now, thank you!
